'\" t
.\"     Title: Kirbydownload
.\"    Author: Uwe Gehring <uwe@imap.cc>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 05/23/2020
.\"    Manual: kirbydownload User Manual
.\"    Source: kirbydownload
.\"  Language: English
.\"
.TH "KIRBYDOWNLOAD" "1" "05/23/2020" "kirbydownload" "kirbydownload User Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kirbydownload \- program to select and download a Kirby kit
.SH "SYNOPSIS"
.HP \w'\fBkirbydownload\fR\ 'u
\fBkirbydownload\fR [\fB\-d\fR] [\fB\-l\fR] [\fB\-f\fR] [\fB\-k\fR\ {\fBstarterkit\fR\ |\ \fBplainkit\fR}] [\fB\-v\fR\ {\fBcurrent\fR\ |\ \fIversionnumber\fR}] [\fB\-t\fR\ \fItargetdir\fR]
.HP \w'\fBkirbydownload\fR\ 'u
\fBkirbydownload\fR [\fB\-h\fR]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBkirbydownload\fR
command, which is part of the
\fBkirbytools\fR(1)
package\&.
.PP
\fBkirbydownload\fR
is a program that will download a Kirby package from Github to your local machine\&. You can choose between the starterkit and the plainkit package and you can select the version which should be downloaded\&. You can also specify the directory where the package will be downloaded to\&.
.PP
Default values for these options will be set by the
\fBkirbyconfigure\fR(1)
program, which will be called upon first invocation of any of the
kirbytools
programs\&. The values will be saved in a file
$HOME/\&.kirbyrc\&.
.SH "OPTIONS"
.PP
The program follows the usual GNU command line syntax, options always starting with a dash (`\-\*(Aq)\&.
.PP
\fB\-h\fR
.RS 4
Show summary of options\&.
.RE
.PP
\fB\-d\fR
.RS 4
Show debugging information\&.
.RE
.PP
\fB\-l\fR
.RS 4
Extract the kirby program directory of the kit to a defined location\&. The location defaults to the value of
\fBKIRBYLIBDIR\fR
(appended with the versionnumber), which has been configured by the
\fBkirbyconfigure\fR(1)
program and which is saved in the file
$HOME/\&.kirbyrc\&.
.sp
This makes sense if you would like to create multiple virtual hosts which are based on one Kirby version\&. The kirby program directory will then only be linked into the virtual host folder\&. See
https://getkirby\&.com/docs/cookbook/setup/multisite\-variant
for further details\&.
.RE
.PP
\fB\-f\fR
.RS 4
Force download even if the package is already downloaded\&.
.RE
.PP
\fB\-k \fR\fB\fBstarterkit\fR\fR\fB|\fR\fB\fBplainkit\fR\fR
.RS 4
Specify which Kirby
\fIkit\fR
to download\&. Defaults to the value of
\fBKIRBYKIT\fR, which has been configured by the
\fBkirbyconfigure\fR(1)
program and which is saved in the file
$HOME/\&.kirbyrc\&.
.RE
.PP
\fB\-v \fR\fB\fBcurrent\fR\fR\fB|\fR\fB\fIversionnumber\fR\fR
.RS 4
Specify which Kirby
\fIversion\fR
to download\&. Defaults to value of
\fBKIRBYVERSION\fR, which has been configured by the
\fBkirbyconfigure\fR(1)
program and which is saved in the file
$HOME/\&.kirbyrc\&.
.sp
If
\fBcurrent\fR
is selected, always the most recent version is downloaded\&. Otherwise a valid versionnumber has to be specified\&.
.RE
.PP
\fB\-t \fR\fB\fItargetdir\fR\fR
.RS 4
Specify the directory where downloads will be saved\&. Defaults to the value of
\fBKIRBYDOWNLOADDIR\fR, which has been configured by the
\fBkirbyconfigure\fR(1)
program and which is saved in the file
$HOME/\&.kirbyrc\&.
.sp
The downloaded package is named
\fIpackage\fR\-\fIversion\fR\&.tar\&.gz\&.
.RE
.SH "FILES"
.PP
/etc/foo\&.conf
.RS 4
The system\-wide configuration file to control the behaviour of
kirbydownload\&. See
\fBfoo.conf\fR(5)
for further details\&.
.RE
.PP
${HOME}/\&.foo\&.conf
.RS 4
The per\-user configuration file to control the behaviour of
kirbydownload\&. See
\fBfoo.conf\fR(5)
for further details\&.
.RE
.SH "ENVIRONMENT"
.PP
\fBFOO_CONF\fR
.RS 4
If used, the defined file is used as configuration file (see also
the section called \(lqFILES\(rq)\&.
.RE
.SH "DIAGNOSTICS"
.PP
The following diagnostics may be issued on
stderr:
.PP
Bad configuration file\&. Exiting\&.
.RS 4
The configuration file seems to contain a broken configuration line\&. Use the
\fB\-\-verbose\fR
option, to get more info\&.
.RE
.PP
\fBkirbydownload\fR
provides some return codes, that can be used in scripts:
.\" line length increase to cope w/ tbl weirdness
.ll +(\n(LLu * 62u / 100u)
.TS
ll.
\fICode\fR	\fIDiagnostic\fR
T{
\fB0\fR
T}	T{
Program exited successfully\&.
T}
T{
\fB1\fR
T}	T{
The configuration file seems to be broken\&.
T}
.TE
.\" line length decrease back to previous value
.ll -(\n(LLu * 62u / 100u)
.sp
.SH "BUGS"
.PP
The program is currently limited to only work with the
foobar
library\&.
.PP
The upstreams
BTS
can be found at
\m[blue]\fB\%http://bugzilla.foo.tld\fR\m[]\&.
.SH "SEE ALSO"
.PP
\fBbar\fR(1),
\fBbaz\fR(1),
\fBfoo.conf\fR(5)
.PP
The programs are documented fully by
The Rise and Fall of a Fooish Bar
available via the
\fBinfo\fR(1)
system\&.
.SH "AUTHOR"
.PP
\fBUwe Gehring\fR <\&uwe@imap\&.cc\&>
.RS 4
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2020 Uwe Gehring
.br
.PP
This manual page was written for the Debian system (and may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or (at your option) any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common\-licenses/GPL\&.
.sp
