'\" t
.\"     Title: Kirbydeinstall
.\"    Author: Uwe Gehring <adspectus@fastmail.com>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 06/02/2020
.\"    Manual: kirbydeinstall User Manual
.\"    Source: kirbydeinstall
.\"  Language: English
.\"
.TH "KIRBYDEINSTALL" "1" "06/02/2020" "kirbydeinstall" "kirbydeinstall User Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kirbydeinstall \- Script to delete a Kirby vhost
.SH "SYNOPSIS"
.HP \w'\fBkirbydeinstall\fR\ 'u
\fBkirbydeinstall\fR [\fB\-d\fR] [\fB\-w\fR\ \fIvhost\fR]
.HP \w'\fBkirbydeinstall\fR\ 'u
\fBkirbydeinstall\fR [\fB\-h\fR]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBkirbydeinstall\fR
command, which is part of the
\fBkirbytools\fR(1)
package\&.
.PP
\fBkirbydeinstall\fR
is a script that will deinstall a Kirby virtual host\&. Multiple virtual hosts can be deinstalled at once by supplying a wildcard expression for the virtual host name\&. However, you have to confirm the deinstallation of every single virtual host\&.
.PP
Optionally, you can remove the virtual host configuration file(s) as well\&. Confirmation must be given to every file\&.
.SH "OPTIONS"
.PP
The script follows the usual GNU command line syntax, options always starting with a dash (`\-\*(Aq)\&.
.PP
\fB\-h\fR
.RS 4
Show summary of options\&.
.RE
.PP
\fB\-d\fR
.RS 4
Show debugging information\&.
.RE
.PP
\fB\-w \fR\fB\fIvhost\fR\fR
.RS 4
Specify the name of the
\fIvirtual host\fR
to deinstall\&. You can easiliy find any given virtual host by using bash\*(Aqs tab completion functionality\&. Hitting <tab> once will complete the name if it is unambiguous\&. Hitting <tab> twice will show all possible completions\&.
.sp
It is possible to use wildcards here\&. Hence using
\(lqkirby\-*\(rq
will deinstall all Kirby virtual hosts which have been created with the
\fBkirbytools\fR(1)
package (supposed you did not change the default value for $KIRBYSUFFIX)\&.
.RE
.SH "FILES"
.PP
/etc/kirbytools/kirbyrc
.RS 4
The system\-wide configuration file to control the behaviour of
kirbydeinstall\&.
.RE
.PP
${HOME}/\&.kirbyrc
.RS 4
The per\-user configuration file to control the behaviour of
kirbydeinstall\&. This file will be created by the
\fBkirbyconfigure\fR
script (see
\fBkirbyconfigure\fR(1)) if it does not exist\&.
.RE
.SH "BUGS"
.PP
Currently, only Kirby 3 starterkits and plainkits are supported\&.
.PP
The programs are currently optimized to work with the
apache2
httpd\&.
.PP
Some functionality requires root (or sudo as root) access\&.
.SH "SEE ALSO"
.PP
\fBkirbyconfigure\fR(1),
\fBkirbydownload\fR(1),
\fBkirbyinstall\fR(1),
\fBkirbysetup\fR(1),
\fBkirbytools\fR(1)
.SH "AUTHOR"
.PP
\fBUwe Gehring\fR <\&adspectus@fastmail\&.com\&>
.RS 4
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2020 Uwe Gehring
.br
.PP
This manual page was written for the Debian system (and may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or (at your option) any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common\-licenses/GPL\&.
.sp
